# Bank Customer Churn Prediction Using Machine Learning

#Loading the dataset

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [3]:
df = pd.read_csv("/content/drive/MyDrive/Data/Churn_Modelling.csv")

In [4]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [5]:
tf.__version__

'2.9.2'

In [6]:
x = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

In [7]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [8]:
y

array([1, 0, 1, ..., 1, 1, 0])

#Data Wrangling

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le = LabelEncoder()

In [11]:
x[:, 1] = le.fit_transform(x[:,1])

In [12]:
x

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [13]:
x[45]

array([776, 1, 'Female', 32, 4, 109421.13, 2, 1, 1, 126517.46],
      dtype=object)

In [14]:
x[:, 2] = le.fit_transform(x[:,2])

In [15]:
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [16]:
x[45]

array([776, 1, 0, 32, 4, 109421.13, 2, 1, 1, 126517.46], dtype=object)

In [17]:
x[5]

array([645, 2, 1, 44, 8, 113755.78, 2, 1, 0, 149756.71], dtype=object)

In [18]:
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [19]:
x.shape

(10000, 10)

###Splitting Data

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state=0)

In [22]:
x_test.shape

(2000, 10)

###Scaling Data

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
sc = StandardScaler()

In [25]:
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [26]:
x_test

array([[-0.56129438,  0.28034192, -1.11339196, ...,  0.66011376,
         0.97628121,  1.62185911],
       [-1.33847768, -0.93853599, -1.11339196, ...,  0.66011376,
        -1.02429504,  0.504204  ],
       [ 0.58347561,  1.49921982, -1.11339196, ...,  0.66011376,
         0.97628121, -0.41865644],
       ...,
       [-0.76084144,  1.49921982,  0.8981563 , ...,  0.66011376,
        -1.02429504,  0.72775202],
       [-0.0046631 ,  0.28034192,  0.8981563 , ...,  0.66011376,
         0.97628121, -1.54162886],
       [-0.81335383,  0.28034192,  0.8981563 , ...,  0.66011376,
        -1.02429504,  1.62356528]])

#Building ANN

In [27]:
ann = tf.keras.models.Sequential()

###Input Layer and 1st Hidden Layer

In [28]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

###2nd Hidden Layer

In [29]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

###O/P Layer

In [30]:
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

#Compiling the ANN

In [31]:
ann.compile(optimizer = "adam", loss='binary_crossentropy', metrics= ['accuracy'])

In [32]:
ann.fit(x_train, y_train, batch_size = 36, epochs = 25)

Epoch 1/25
223/223 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7839
Epoch 2/25
223/223 [==============================] - 0s 2ms/step - loss: 0.4724 - accuracy: 0.7954
Epoch 3/25
223/223 [==============================] - 0s 2ms/step - loss: 0.4522 - accuracy: 0.7968
Epoch 4/25
223/223 [==============================] - 0s 2ms/step - loss: 0.4373 - accuracy: 0.8025
Epoch 5/25
223/223 [==============================] - 0s 2ms/step - loss: 0.4248 - accuracy: 0.8080
Epoch 6/25
223/223 [==============================] - 0s 2ms/step - loss: 0.4137 - accuracy: 0.8149
Epoch 7/25
223/223 [==============================] - 0s 2ms/step - loss: 0.4046 - accuracy: 0.8177
Epoch 8/25
223/223 [==============================] - 0s 2ms/step - loss: 0.3962 - accuracy: 0.8181
Epoch 9/25
223/223 [==============================] - 0s 2ms/step - loss: 0.3885 - accuracy: 0.8217
Epoch 10/25
223/223 [==============================] - 0s 2ms/step - loss: 0.3822 - accuracy: 0.8242

In [33]:
y_pred = ann.predict(x_test)

63/63 [==============================] - 0s 1ms/step


In [34]:
y_pred = y_pred > 0.5

In [35]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [36]:
y_test

array([0, 1, 0, ..., 0, 0, 0])

In [37]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [38]:
accuracy_score(y_test, y_pred)

0.8635

In [39]:
confusion_matrix(y_test, y_pred)

array([[1544,   51],
       [ 222,  183]])

Task

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer ?

In [41]:
print(ann.predict(sc.transform([[1, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 44ms/step
[[False]]
